#!/bin/bash
set -e

# Jenkins Plugin Development Feature Installation Script
# This script configures Maven settings.xml for Jenkins plugin development

echo "Activating feature 'jenkins-plugin-dev'"

# Parse options from environment variables (auto-capitalized and sanitized by devcontainer spec)
REPOSITORY_URL="${REPOSITORYURL:-https://repo.jenkins-ci.org/public/}"
ENABLE_INCREMENTAL="${ENABLEINCREMENTALBUILD:-false}"
MAVEN_VERSION="${MAVENVERSION:-latest}"
MIRROR_ID="${MIRRORID:-repo.jenkins-ci.org}"
ADDITIONAL_PROFILES="${ADDITIONALPROFILES:-}"
INSTALL_LOCATION="${INSTALLLOCATION:-user}"
ENABLE_OFFLINE="${ENABLEOFFLINEMODE:-false}"

echo "Configuration:"
echo "  Repository URL: ${REPOSITORY_URL}"
echo "  Jenkins Incrementals: ${ENABLE_INCREMENTAL}"
echo "  Maven Version: ${MAVEN_VERSION}"
echo "  Mirror ID: ${MIRROR_ID}"
echo "  Install Location: ${INSTALL_LOCATION}"
echo "  Offline Mode: ${ENABLE_OFFLINE}"

# Function to check if Maven is installed
check_maven() {
    if command -v mvn &> /dev/null; then
        echo "Maven is already installed: $(mvn --version | head -n 1)"
        return 0
    else
        return 1
    fi
}

# Function to install Maven if needed
install_maven() {
    if [ "${MAVEN_VERSION}" = "latest" ]; then
        MAVEN_VERSION="3.9.9"
    elif [ "${MAVEN_VERSION}" = "3.9" ]; then
        MAVEN_VERSION="3.9.9"
    elif [ "${MAVEN_VERSION}" = "3.8" ]; then
        MAVEN_VERSION="3.8.8"
    fi

    echo "Installing Maven ${MAVEN_VERSION}..."
    
    # Ensure curl is available
    if ! command -v curl &> /dev/null; then
        echo "Installing curl..."
        apt-get update -y
        apt-get install -y curl ca-certificates
    fi
    
    # Download and install Maven
    MAVEN_HOME="/usr/share/maven"
    MAVEN_DOWNLOAD_URL="https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz"
    
    # Create temporary directory
    TMP_DIR=$(mktemp -d)
    cd "${TMP_DIR}"
    
    # Download Maven
    curl -fsSL "${MAVEN_DOWNLOAD_URL}" -o maven.tar.gz
    
    # Extract and install
    mkdir -p "${MAVEN_HOME}"
    tar -xzf maven.tar.gz -C "${MAVEN_HOME}" --strip-components=1
    
    # Create symlink
    ln -sf "${MAVEN_HOME}/bin/mvn" /usr/local/bin/mvn
    
    # Cleanup
    cd - > /dev/null
    rm -rf "${TMP_DIR}"
    
    echo "Maven ${MAVEN_VERSION} installed successfully"
}

# Function to generate settings.xml content
generate_settings_xml() {
    cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                              http://maven.apache.org/xsd/settings-1.0.0.xsd">
  
  <!-- Generated by jenkins-plugin-dev devcontainer feature -->
  
  <profiles>
    <profile>
      <id>jenkins</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <repositories>
        <repository>
          <id>${MIRROR_ID}</id>
          <url>${REPOSITORY_URL}</url>
          <releases>
            <enabled>true</enabled>
          </releases>
          <snapshots>
            <enabled>true</enabled>
          </snapshots>
        </repository>
      </repositories>
      <pluginRepositories>
        <pluginRepository>
          <id>${MIRROR_ID}</id>
          <url>${REPOSITORY_URL}</url>
          <releases>
            <enabled>true</enabled>
          </releases>
          <snapshots>
            <enabled>true</enabled>
          </snapshots>
        </pluginRepository>
      </pluginRepositories>
    </profile>
EOF

    # Add incremental build profile if enabled
    if [ "${ENABLE_INCREMENTAL}" = "true" ]; then
        cat <<EOF
    <profile>
      <id>jenkins-incremental</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <repositories>
        <repository>
          <id>incrementals</id>
          <url>https://repo.jenkins-ci.org/incrementals/</url>
          <releases>
            <enabled>false</enabled>
          </releases>
          <snapshots>
            <enabled>true</enabled>
          </snapshots>
        </repository>
      </repositories>
      <pluginRepositories>
        <pluginRepository>
          <id>incrementals</id>
          <url>https://repo.jenkins-ci.org/incrementals/</url>
          <releases>
            <enabled>false</enabled>
          </releases>
          <snapshots>
            <enabled>true</enabled>
          </snapshots>
        </pluginRepository>
      </pluginRepositories>
    </profile>
EOF
    fi

    # Close profiles tag
    echo "  </profiles>"
    
    # Add active profiles
    echo "  <activeProfiles>"
    echo "    <activeProfile>jenkins</activeProfile>"
    
    if [ "${ENABLE_INCREMENTAL}" = "true" ]; then
        echo "    <activeProfile>jenkins-incremental</activeProfile>"
    fi
    
    # Add additional profiles if specified
    if [ -n "${ADDITIONAL_PROFILES}" ]; then
        IFS=',' read -ra PROFILES <<< "${ADDITIONAL_PROFILES}"
        for profile in "${PROFILES[@]}"; do
            # Trim whitespace
            profile=$(echo "${profile}" | xargs)
            if [ -n "${profile}" ]; then
                echo "    <activeProfile>${profile}</activeProfile>"
            fi
        done
    fi
    
    echo "  </activeProfiles>"
    
    # Add offline mode if enabled
    if [ "${ENABLE_OFFLINE}" = "true" ]; then
        echo "  <offline>true</offline>"
    fi
    
    # Close settings tag
    echo "</settings>"
}

# Function to install settings.xml to a specific location
install_settings_xml() {
    local target_dir="$1"
    local settings_file="${target_dir}/settings.xml"
    
    echo "Installing settings.xml to ${settings_file}"
    
    # Create directory if it doesn't exist
    mkdir -p "${target_dir}"
    
    # Generate and write settings.xml
    generate_settings_xml > "${settings_file}"
    
    # Set appropriate permissions
    chmod 644 "${settings_file}"
    
    echo "✓ Settings.xml installed successfully at ${settings_file}"
}

# Main installation logic

# Check and install Maven if needed
if ! check_maven; then
    echo "Maven not found. Installing..."
    install_maven
else
    echo "Maven is already available, skipping installation"
fi

# Install settings.xml based on location preference
case "${INSTALL_LOCATION}" in
    "user")
        # Install to user's home directory
        if [ -n "${_REMOTE_USER}" ]; then
            USER_HOME=$(getent passwd "${_REMOTE_USER}" | cut -d: -f6)
        else
            USER_HOME="${HOME}"
        fi
        install_settings_xml "${USER_HOME}/.m2"
        ;;
    "system")
        # Install to system-wide location
        install_settings_xml "/etc/maven"
        ;;
    "both")
        # Install to both locations
        if [ -n "${_REMOTE_USER}" ]; then
            USER_HOME=$(getent passwd "${_REMOTE_USER}" | cut -d: -f6)
        else
            USER_HOME="${HOME}"
        fi
        install_settings_xml "${USER_HOME}/.m2"
        install_settings_xml "/etc/maven"
        ;;
    *)
        echo "Error: Invalid install location '${INSTALL_LOCATION}'"
        exit 1
        ;;
esac

# Also install for root user if we're not root and user location is selected
if [ "${INSTALL_LOCATION}" = "user" ] && [ "$(id -u)" -ne 0 ] && [ -d "/root" ]; then
    echo "Also installing settings.xml for root user..."
    install_settings_xml "/root/.m2"
fi

echo ""
echo "=========================================="
echo "Jenkins Plugin Development Feature Setup Complete!"
echo "=========================================="
echo ""
echo "Maven is configured with:"
echo "  - Jenkins repository: ${REPOSITORY_URL}"
echo "  - Mirror ID: ${MIRROR_ID}"
if [ "${ENABLE_INCREMENTAL}" = "true" ]; then
    echo "  - Incremental builds: ENABLED"
fi
if [ "${ENABLE_OFFLINE}" = "true" ]; then
    echo "  - Offline mode: ENABLED"
fi
echo ""
echo "You can now build Jenkins plugins with 'mvn clean verify'"
echo ""
